kind: Service
apiVersion: v1
metadata:
  labels:
    app: ecp-cdash
  name: ecp-cdash
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ecp-cdash
    deploymentconfig: ecp-cdash
